/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.form;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sistema.dao.ClienteDao;
import sistema.model.Cliente;

/**
 *
 * @author marcos
 */
public class FormClientes extends javax.swing.JFrame {

  DefaultTableModel dtmTabela = new DefaultTableModel(null, new String[]{"ID", "Nome", "Telefone", "Email"});

  private List<Cliente> clientes;
  private ListSelectionModel lsmClientes;
  private Cliente clienteSelecionado = new Cliente();

  /**
   * Creates new form FormConsultaCliente
   */
  public FormClientes() {
    initComponents();
    consultarCliente();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabela = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    tfConsulta = new javax.swing.JTextField();
    btConsultar = new javax.swing.JButton();
    btIncluir = new javax.swing.JButton();
    btEditar = new javax.swing.JButton();
    btDeletar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastros de Clientes"));

    tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    lsmClientes = tabela.getSelectionModel();
    lsmClientes.addListSelectionListener(new ListSelectionListener(){
      public void valueChanged(ListSelectionEvent e){
        if(!e.getValueIsAdjusting()){
          linhaTabela(tabela);
        }
      }
    });
    tabela.setModel(dtmTabela);
    jScrollPane1.setViewportView(tabela);

    jLabel1.setText("Localizar");

    btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search-32.png"))); // NOI18N
    btConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btConsultarActionPerformed(evt);
      }
    });

    btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/New document.png"))); // NOI18N
    btIncluir.setText("Incluir");
    btIncluir.setToolTipText("");
    btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btIncluir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    btIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btIncluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btIncluirActionPerformed(evt);
      }
    });

    btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modify.png"))); // NOI18N
    btEditar.setText("Editar");
    btEditar.setToolTipText("");
    btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btEditarActionPerformed(evt);
      }
    });

    btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash.png"))); // NOI18N
    btDeletar.setText("Deletar");
    btDeletar.setToolTipText("");
    btDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btDeletar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    btDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btDeletar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btDeletarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tfConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel1))
            .addGap(38, 38, 38)
            .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(tfConsulta)))
          .addComponent(btDeletar)
          .addComponent(btEditar)
          .addComponent(btIncluir))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    setSize(new java.awt.Dimension(758, 454));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
    consultarCliente();
  }//GEN-LAST:event_btConsultarActionPerformed

  private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
    FormCadClientes formCadClientes = new FormCadClientes();
    formCadClientes.setFormClientes(this);
    formCadClientes.setVisible(true);
  }//GEN-LAST:event_btIncluirActionPerformed

  private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
    if (tabela.getSelectedRow() != -1) {
      FormCadClientes formEditClientes = new FormCadClientes();
      formEditClientes.setId(clienteSelecionado.getId());
      formEditClientes.preencheFormulario(clienteSelecionado);
      formEditClientes.setEdit(true);
      formEditClientes.setFormClientes(this);
      formEditClientes.setVisible(true);
    }else{
      JOptionPane.showMessageDialog(this, "Um registro deve ser selecionado para alteração", "Alerta", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btEditarActionPerformed

  private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
    if (tabela.getSelectedRow() != -1) {
      int res = JOptionPane.showConfirmDialog(null, "Deseja Excluir o registro Selecionado?", "Excluir", JOptionPane.YES_NO_OPTION);
      if (res == JOptionPane.YES_OPTION) {
        ClienteDao clienteDao = new ClienteDao();
        if (clienteDao.excluir(clienteSelecionado.getId())) {
          JOptionPane.showMessageDialog(this, "Registro deletado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
          consultarCliente();
        }
      }
    } else {
      JOptionPane.showMessageDialog(this, "Um registro deve ser selecionado para exclusão", "Alerta", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btDeletarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormClientes().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btConsultar;
  private javax.swing.JButton btDeletar;
  private javax.swing.JButton btEditar;
  private javax.swing.JButton btIncluir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tabela;
  private javax.swing.JTextField tfConsulta;
  // End of variables declaration//GEN-END:variables

  public void consultarCliente() {
    ClienteDao cliDao = new ClienteDao();
    clientes = cliDao.listar("%" + tfConsulta.getText() + "%");
    preencherTabela(clientes);
  }

  private void preencherTabela(List<Cliente> clientes) {
    while (dtmTabela.getRowCount() > 0) {
      dtmTabela.setRowCount(0);
    }
    if (clientes.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Registro não localizado.");
    } else {
      String[] linha = new String[]{null, null};
      for (int i = 0; i < clientes.size(); i++) {
        dtmTabela.addRow(linha);
        dtmTabela.setValueAt(clientes.get(i).getId(), i, 0);
        dtmTabela.setValueAt(clientes.get(i).getNome(), i, 1);
        dtmTabela.setValueAt(clientes.get(i).getTelefone(), i, 2);
        dtmTabela.setValueAt(clientes.get(i).getEmail(), i, 3);
      }
    }
  }

  public void linhaTabela(JTable tabela) {
    if (tabela.getSelectedRow() != -1) {
      clienteSelecionado.setId(clientes.get(tabela.getSelectedRow()).getId());
      clienteSelecionado.setNome(clientes.get(tabela.getSelectedRow()).getNome());
      clienteSelecionado.setCPF(clientes.get(tabela.getSelectedRow()).getCPF());
      clienteSelecionado.setRG(clientes.get(tabela.getSelectedRow()).getRG());
      clienteSelecionado.setDataNascimento(clientes.get(tabela.getSelectedRow()).getDataNascimento());
      clienteSelecionado.setTelefone(clientes.get(tabela.getSelectedRow()).getTelefone());
      clienteSelecionado.setEmail(clientes.get(tabela.getSelectedRow()).getEmail());
      clienteSelecionado.setEndereco(clientes.get(tabela.getSelectedRow()).getEndereco());
    } else {
      clienteSelecionado.setId(0);
      clienteSelecionado.setNome("");
    }
  }

}
