/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.form;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sistema.dao.CategoriaDao;
import sistema.model.Categoria;

/**
 *
 * @author marcos
 */
public class FormLocalizaCategoria extends javax.swing.JFrame {

  DefaultTableModel dtmTabela = new DefaultTableModel(null, new String[]{"ID", "Nome"});

  private List<Categoria> categorias;
  private ListSelectionModel lsmCategorias;
  private FormCadProduto formCadProduto;

  /**
   * Creates new form FormConsultaCliente
   */
  public FormLocalizaCategoria() {
    initComponents();
    try {
      consultarCategoria();
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(FormLocalizaCategoria.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(FormLocalizaCategoria.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabela = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    tfConsulta = new javax.swing.JTextField();
    btConsultar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localizar Produto / Serviço"));

    tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    lsmCategorias = tabela.getSelectionModel();
    lsmCategorias.addListSelectionListener(new ListSelectionListener(){
      public void valueChanged(ListSelectionEvent e){
        if(!e.getValueIsAdjusting()){
          linhaTabela(tabela);
        }
      }
    });
    tabela.setModel(dtmTabela);
    jScrollPane1.setViewportView(tabela);

    jLabel1.setText("Localizar");

    btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search-32.png"))); // NOI18N
    btConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btConsultarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(tfConsulta)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(289, 333, Short.MAX_VALUE))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tfConsulta))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    setSize(new java.awt.Dimension(450, 454));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
    try {
      consultarCategoria();
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(FormLocalizaCategoria.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(FormLocalizaCategoria.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btConsultarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormLocalizaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormLocalizaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormLocalizaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormLocalizaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormLocalizaCategoria().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btConsultar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tabela;
  private javax.swing.JTextField tfConsulta;
  // End of variables declaration//GEN-END:variables

  private void consultarCategoria() throws ClassNotFoundException, SQLException {
    CategoriaDao categoriaDao = new CategoriaDao();
    categorias = categoriaDao.listar("%" + tfConsulta.getText() + "%");
    preencherTabela(categorias);
  }

  private void preencherTabela(List<Categoria> categorias) {
    while (dtmTabela.getRowCount() > 0) {
      dtmTabela.setRowCount(0);
    }
    if (categorias.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Registro não localizado.");
    } else {
      String[] linha = new String[]{null, null};
      for (int i = 0; i < categorias.size(); i++) {
        dtmTabela.addRow(linha);
        dtmTabela.setValueAt(categorias.get(i).getCategoriaId(), i, 0);
        dtmTabela.setValueAt(categorias.get(i).getCategoriaNome(), i, 1);
      }
    }
  }

  public void linhaTabela(JTable tabela) {
   Categoria c = new Categoria();
    if(tabela.getSelectedRow() != -1){
      c.setCategoriaId(categorias.get(tabela.getSelectedRow()).getCategoriaId());
      c.setCategoriaNome(categorias.get(tabela.getSelectedRow()).getCategoriaNome());
      if(formCadProduto != null){
        formCadProduto.preencheCategoria(c);
        this.dispose();
      }
      this.dispose();
    }else{
      c.setCategoriaId(0);
      c.setCategoriaNome("");
    }
  }

  void setFormCadProduto(FormCadProduto formCadProduto) {
    this.formCadProduto = formCadProduto;
  }

}
