/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.form;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistema.dao.CategoriaDao;
import sistema.dao.ProdutoDao;
import sistema.model.Categoria;
import sistema.model.Produto;

/**
 *
 * @author matsui
 */
public class FormCadProduto extends javax.swing.JFrame {
  private FormProdutos formProdutos;
  private Boolean edit = false;
  private Integer id = 0;
 
  /**
   * Creates new form FormClientes
   */
  public FormCadProduto() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    btSalvar = new javax.swing.JButton();
    btCancelar = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    tfProduto = new javax.swing.JTextField();
    tfCusto = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    tfVenda = new javax.swing.JTextField();
    tfQuantidade = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    tfCategoriaProduto = new javax.swing.JTextField();
    btLocCategoria = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    tfIdCategoria = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    cbTipo = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    tfDescricao = new javax.swing.JTextArea();
    jLabel9 = new javax.swing.JLabel();
    cbStatus = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

    jLabel4.setText("Categoria");

    btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Yes.png"))); // NOI18N
    btSalvar.setText("Salvar");
    btSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSalvarActionPerformed(evt);
      }
    });

    btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete.png"))); // NOI18N
    btCancelar.setText("Cancelar");
    btCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCancelarActionPerformed(evt);
      }
    });

    jLabel2.setText("Produto");

    tfCusto.setToolTipText("");

    jLabel3.setText("Valor Custo");

    jLabel5.setText("Valor Venda");

    jLabel6.setText("Quantidade");

    jLabel7.setText("Descrição");

    tfCategoriaProduto.setEditable(false);

    btLocCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search-32.png"))); // NOI18N
    btLocCategoria.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btLocCategoriaActionPerformed(evt);
      }
    });

    jLabel8.setText("ID Categoria");

    tfIdCategoria.setEditable(false);

    jLabel1.setText("Tipo");

    cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produto", "Serviço" }));

    tfDescricao.setColumns(20);
    tfDescricao.setRows(5);
    jScrollPane1.setViewportView(tfDescricao);

    jLabel9.setText("Status");

    cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desativado", "Ativado" }));
    cbStatus.setSelectedIndex(1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfIdCategoria))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                          .addComponent(tfCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(btLocCategoria))
                        .addComponent(jLabel4))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addComponent(jLabel3)
                      .addGap(96, 96, 96)
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addGap(18, 18, 18)
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                  .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(tfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(323, 323, 323)))
              .addComponent(jLabel9))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btLocCategoria)
          .addComponent(tfCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addComponent(jLabel5)
            .addComponent(jLabel6))
          .addComponent(jLabel1))
        .addGap(4, 4, 4)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btSalvar)
          .addComponent(btCancelar))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
    if (edit) {
      try {
        editarProduto();
      } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(FormCadProduto.class.getName()).log(Level.SEVERE, null, ex);
      }
    } else {
      try {
        cadastrarProduto();
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(FormCadCategorias.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
        Logger.getLogger(FormCadProduto.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }//GEN-LAST:event_btSalvarActionPerformed

  private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btCancelarActionPerformed

  private void btLocCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocCategoriaActionPerformed
    FormLocalizaCategoria formLocalizaCategoria = new FormLocalizaCategoria();
    formLocalizaCategoria.setFormCadProduto(this);
    formLocalizaCategoria.setVisible(true);
  }//GEN-LAST:event_btLocCategoriaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormCadProduto().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btCancelar;
  private javax.swing.JButton btLocCategoria;
  private javax.swing.JButton btSalvar;
  private javax.swing.JComboBox<String> cbStatus;
  private javax.swing.JComboBox<String> cbTipo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField tfCategoriaProduto;
  private javax.swing.JTextField tfCusto;
  private javax.swing.JTextArea tfDescricao;
  private javax.swing.JTextField tfIdCategoria;
  private javax.swing.JTextField tfProduto;
  private javax.swing.JTextField tfQuantidade;
  private javax.swing.JTextField tfVenda;
  // End of variables declaration//GEN-END:variables
 
  public void preencheFormulario(Produto produto) {
    tfIdCategoria.setText(produto.getCategoria().getCategoriaId().toString());
    tfCategoriaProduto.setText(produto.getCategoria().getCategoriaNome());
    tfProduto.setText(produto.getNome());
    cbTipo.setSelectedIndex(produto.getTipo());
    tfCusto.setText(produto.getValorCusto().toString());
    tfVenda.setText(produto.getValorVenda().toString());
    tfVenda.setText(produto.getValorVenda().toString());
    tfQuantidade.setText(produto.getQuantidade().toString());
    tfQuantidade.setEnabled(false);
    tfDescricao.setText(produto.getDescricao());
    cbStatus.setSelectedIndex(produto.getStatus());
  }
  
  public void setEdit(Boolean edit) {
    this.edit = edit;
  }

  void setFormProduto(FormProdutos formProdutos) {
    this.formProdutos = formProdutos;
  }
  
  public void setId(Integer id) {
    this.id = id;
  }
  
  private void editarProduto() throws ClassNotFoundException, SQLException {
    if (id <= 0) {
      JOptionPane.showMessageDialog(this, "Nenhum Registro foi Informado", "Erro", JOptionPane.ERROR_MESSAGE);
    } else if (tfIdCategoria.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Informe uma Categoria", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfProduto.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "O Campo produto deve ser preenchido", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfVenda.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "O Valor de venda deve ser informado", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfQuantidade.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "A Quantidade deve ser informada", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else {
      Produto produto = new Produto();
      ProdutoDao produtoDao = new ProdutoDao();
      Categoria categoria = new Categoria();
      categoria.setCategoriaId(Integer.parseInt(tfIdCategoria.getText()));
      Double custo = Double.parseDouble(tfCusto.getText());
      Double venda = Double.parseDouble(tfVenda.getText());
      produto.setId(id);
      produto.setNome(tfProduto.getText());
      produto.setCategoria(categoria);
      produto.setDescricao(tfDescricao.getText());
      produto.setTipo(cbTipo.getSelectedIndex());
      produto.setValorCusto(custo);
      produto.setValorVenda(venda);
      produto.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
      produto.setStatus(cbStatus.getSelectedIndex());

      if (produtoDao.alterar(produto) == null) {
        JOptionPane.showMessageDialog(this, "Erro ao alterar registro.", "Erro", JOptionPane.ERROR_MESSAGE);
      } else {
        formProdutos.consultarProduto();
        this.dispose();
      }
    }
  }

  private void cadastrarProduto() throws ClassNotFoundException, SQLException {
    if (tfIdCategoria.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Informe uma Categoria", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfProduto.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "O Campo produto deve ser preenchido", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfVenda.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "O Valor de venda deve ser informado", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else if (tfQuantidade.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "A Quantidade deve ser informada", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    } else {
      Produto produto = new Produto();
      ProdutoDao produtoDao = new ProdutoDao();
      Categoria categoria = new Categoria();
      categoria.setCategoriaId(Integer.parseInt(tfIdCategoria.getText()));
      Double custo = Double.parseDouble(tfCusto.getText());
      Double venda = Double.parseDouble(tfVenda.getText());
      
      produto.setNome(tfProduto.getText());
      produto.setCategoria(categoria);
      produto.setId(cbTipo.getSelectedIndex());
      produto.setDescricao(tfDescricao.getText());
      produto.setTipo(cbTipo.getSelectedIndex());
      produto.setValorCusto(custo);
      produto.setValorVenda(venda);
      produto.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
      produto.setStatus(cbStatus.getSelectedIndex());

      if (produtoDao.salvar(produto) == null) {
        JOptionPane.showMessageDialog(this, "Erro ao alterar registro.", "Erro", JOptionPane.ERROR_MESSAGE);
      } else {
        formProdutos.consultarProduto();
        this.dispose();
      }

    }
  }

  void preencheCategoria(Categoria c) {
    tfIdCategoria.setText(String.valueOf(c.getCategoriaId()));
    tfCategoriaProduto.setText(c.getCategoriaNome());
  }
}
