/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.form;

/**
 *
 * @author marcos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
//        setLocationRelativeTo(null);
        setTitle("Sistema Barbearia 1.0");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    CadastrosMenu = new javax.swing.JMenu();
    ClientesMenu = new javax.swing.JMenuItem();
    categoriasMenu = new javax.swing.JMenuItem();
    funcionariosMenu = new javax.swing.JMenuItem();
    produtosMenu = new javax.swing.JMenuItem();
    AgendaMenu = new javax.swing.JMenu();
    AgendamentoMenu = new javax.swing.JMenuItem();
    MovimentacaoMenu = new javax.swing.JMenu();
    VendaMenu = new javax.swing.JMenuItem();
    EstoqueMenu = new javax.swing.JMenu();
    EntradaMenu = new javax.swing.JMenuItem();
    SaidaMenu = new javax.swing.JMenuItem();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(java.awt.Color.darkGray);

    jLabel2.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
    jLabel2.setForeground(java.awt.Color.darkGray);
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Barbearia - SisBarba 1.0");
    jLabel2.setToolTipText("");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo-256.png"))); // NOI18N
    jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    CadastrosMenu.setText("Cadastros");

    ClientesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/People.png"))); // NOI18N
    ClientesMenu.setText("Clientes");
    ClientesMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ClientesMenuActionPerformed(evt);
      }
    });
    CadastrosMenu.add(ClientesMenu);

    categoriasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/List.png"))); // NOI18N
    categoriasMenu.setText("Categorias");
    categoriasMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        categoriasMenuActionPerformed(evt);
      }
    });
    CadastrosMenu.add(categoriasMenu);

    funcionariosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User group.png"))); // NOI18N
    funcionariosMenu.setText("Funcionarios");
    funcionariosMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        funcionariosMenuActionPerformed(evt);
      }
    });
    CadastrosMenu.add(funcionariosMenu);

    produtosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gift.png"))); // NOI18N
    produtosMenu.setText("Produtos");
    produtosMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        produtosMenuActionPerformed(evt);
      }
    });
    CadastrosMenu.add(produtosMenu);

    jMenuBar1.add(CadastrosMenu);

    AgendaMenu.setText("Agenda");

    AgendamentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Calendar.png"))); // NOI18N
    AgendamentoMenu.setText("Agendamentos");
    AgendamentoMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AgendamentoMenuActionPerformed(evt);
      }
    });
    AgendaMenu.add(AgendamentoMenu);

    jMenuBar1.add(AgendaMenu);

    MovimentacaoMenu.setText("Movimentação");

    VendaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
    VendaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cash-register-32.png"))); // NOI18N
    VendaMenu.setText("Venda");
    VendaMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VendaMenuActionPerformed(evt);
      }
    });
    MovimentacaoMenu.add(VendaMenu);

    jMenuBar1.add(MovimentacaoMenu);

    EstoqueMenu.setText("Estoque");

    EntradaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
    EntradaMenu.setText("Entrada");
    EntradaMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        EntradaMenuActionPerformed(evt);
      }
    });
    EstoqueMenu.add(EntradaMenu);

    SaidaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Remove.png"))); // NOI18N
    SaidaMenu.setText("Saida");
    SaidaMenu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaidaMenuActionPerformed(evt);
      }
    });
    EstoqueMenu.add(SaidaMenu);

    jMenuBar1.add(EstoqueMenu);

    setJMenuBar(jMenuBar1);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(298, 298, 298)
        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(330, 330, 330))
      .add(layout.createSequentialGroup()
        .add(180, 180, 180)
        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(211, 211, 211))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(173, 173, 173)
        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(89, 89, 89))
    );

    setSize(new java.awt.Dimension(894, 630));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void VendaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaMenuActionPerformed
        // TODO add your handling code here:
        FormVenda formVenda = new FormVenda();
        formVenda.setVisible(true);
    }//GEN-LAST:event_VendaMenuActionPerformed

  private void ClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesMenuActionPerformed
    FormClientes formClientes = new FormClientes();
    formClientes.setVisible(true);
  }//GEN-LAST:event_ClientesMenuActionPerformed

  private void categoriasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasMenuActionPerformed
    FormCategorias formCategorias = new FormCategorias();
    formCategorias.setVisible(true);
  }//GEN-LAST:event_categoriasMenuActionPerformed

  private void funcionariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosMenuActionPerformed
    FormFuncionarios formFuncionarios = new FormFuncionarios();
    formFuncionarios.setVisible(true);
  }//GEN-LAST:event_funcionariosMenuActionPerformed

  private void produtosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosMenuActionPerformed
    FormProdutos formProdutos = new FormProdutos();
    formProdutos.setVisible(true);
  }//GEN-LAST:event_produtosMenuActionPerformed

  private void AgendamentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendamentoMenuActionPerformed
    FormAgenda formAgenda = new FormAgenda();
    formAgenda.setVisible(true);
  }//GEN-LAST:event_AgendamentoMenuActionPerformed

  private void EntradaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaMenuActionPerformed
    FormEntradaProduto formEntradaProduto = new FormEntradaProduto();
    formEntradaProduto.setVisible(true);
  }//GEN-LAST:event_EntradaMenuActionPerformed

  private void SaidaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaMenuActionPerformed
    FormSaidaProduto formSaidaProduto = new FormSaidaProduto();
    formSaidaProduto.setVisible(true);
  }//GEN-LAST:event_SaidaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu AgendaMenu;
  private javax.swing.JMenuItem AgendamentoMenu;
  private javax.swing.JMenu CadastrosMenu;
  private javax.swing.JMenuItem ClientesMenu;
  private javax.swing.JMenuItem EntradaMenu;
  private javax.swing.JMenu EstoqueMenu;
  private javax.swing.JMenu MovimentacaoMenu;
  private javax.swing.JMenuItem SaidaMenu;
  private javax.swing.JMenuItem VendaMenu;
  private javax.swing.JMenuItem categoriasMenu;
  private javax.swing.JMenuItem funcionariosMenu;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem produtosMenu;
  // End of variables declaration//GEN-END:variables
}
